package hwhh.codegen

import com.squareup.kotlinpoet.BOOLEAN
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.LambdaTypeName
import com.squareup.kotlinpoet.MAP
import com.squareup.kotlinpoet.ParameterSpec
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.SET
import com.squareup.kotlinpoet.STRING
import com.squareup.kotlinpoet.TypeSpec
import com.squareup.kotlinpoet.joinToCode

private const val BANNER = "Generated by generateHookRegistry from the xposed hooker graph."
private const val REGISTRY_FILE = "HookRegistry"

private val HOOK_FEATURE = ClassName(RegistryTarget.SHARED.pkg, "HookFeature")
private val DEBUG_TOGGLE = ClassName(RegistryTarget.SHARED.pkg, HookNames.DEBUG_TOGGLE)
private val DEBUG_PREFS = ClassName(RegistryTarget.SHARED.pkg, HookNames.DEBUG_PREFS)
private val PREFS_DATA = ClassName(
    "com.highcapable.yukihookapi.hook.xposed.prefs.data",
    HookNames.PREFS_DATA,
).parameterizedBy(BOOLEAN)
private val BASE_HOOKER = ClassName("moe.evil.hwhh.xposed.utils", HookNames.BASE_HOOKER)
private val FEATURE_SET = SET.parameterizedBy(HOOK_FEATURE)

internal fun HookGraph.sharedFile() = registryFile(RegistryTarget.SHARED)
    .addType(hookFeatureEnum())
    .addType(debugToggleEnum())
    .build()

internal fun HookGraph.xposedFile() = registryFile(RegistryTarget.XPOSED)
    .addFunction(hookRootOf())
    .addProperty(hookerEdges())
    .build()

private fun registryFile(target: RegistryTarget) = FileSpec.builder(target.pkg, REGISTRY_FILE)
    .indent("    ")
    .addFileComment(BANNER)

private fun HookGraph.hookFeatureEnum() = TypeSpec.enumBuilder(HOOK_FEATURE)
    .primaryConstructor(FunSpec.constructorBuilder().addParameter("key", STRING).build())
    .addProperty(PropertySpec.builder("key", STRING).initializer("key").build())
    .apply {
        roots.forEach { addConstantEnum(featureOf(it), CodeBlock.of("%S", it.name)) }
    }
    .build()

private fun HookGraph.debugToggleEnum() = TypeSpec.enumBuilder(DEBUG_TOGGLE)
    .primaryConstructor(
        FunSpec.constructorBuilder()
            .addParameter("pref", PREFS_DATA)
            .addParameter("requiredBy", FEATURE_SET)
            .build()
    )
    .addProperty(PropertySpec.builder("pref", PREFS_DATA).initializer("pref").build())
    .addProperty(PropertySpec.builder("requiredBy", FEATURE_SET).initializer("requiredBy").build())
    .apply {
        val gates = gates()
        prefs.forEach { pref ->
            addConstantEnum(
                pref,
                CodeBlock.of("%T.%L", DEBUG_PREFS, pref),
                gates.getValue(pref)
                    .map { CodeBlock.of("%T.%L", HOOK_FEATURE, it) }
                    .toSetLiteral(),
            )
        }
    }
    .addFunction(
        FunSpec.builder("isUnlocked")
            .addParameter(
                "isFeatureEnabled",
                LambdaTypeName.get(
                    parameters = listOf(ParameterSpec.unnamed(HOOK_FEATURE)),
                    returnType = BOOLEAN,
                ),
            )
            .returns(BOOLEAN)
            .addStatement("return requiredBy.isEmpty() || requiredBy.any(isFeatureEnabled)")
            .build()
    )
    .build()

private fun HookGraph.hookRootOf() = FunSpec.builder("hookRootOf")
    .addModifiers(KModifier.INTERNAL)
    .addParameter("feature", HOOK_FEATURE)
    .returns(BASE_HOOKER)
    .beginControlFlow("return when (feature)")
    .apply {
        roots.forEach {
            addStatement("%T.%L -> %T", HOOK_FEATURE, featureOf(it), ClassName(it.pkg, it.name))
        }
    }
    .endControlFlow()
    .build()

private fun HookGraph.hookerEdges() = PropertySpec
    .builder("HOOKER_EDGES", MAP.parameterizedBy(STRING, SET.parameterizedBy(STRING)))
    .addModifiers(KModifier.INTERNAL)
    .initializer(
        nodes.values.sortedBy(HookerNode::name).map { node ->
            CodeBlock.of(
                "%S to %L",
                node.name,
                node.deps.sorted().map { CodeBlock.of("%S", it) }.toSetLiteral(),
            )
        }.joinToCode(separator = ",\n", prefix = "mapOf(\n", suffix = ",\n)")
    )
    .build()

private fun TypeSpec.Builder.addConstantEnum(name: String, vararg args: CodeBlock) =
    addEnumConstant(
        name,
        TypeSpec.anonymousClassBuilder()
            .apply { args.forEach { addSuperclassConstructorParameter(it) } }
            .build(),
    )

private fun List<CodeBlock>.toSetLiteral() = when {
    isEmpty() -> CodeBlock.of("emptySet()")
    else -> joinToCode(prefix = "setOf(", suffix = ")")
}
